### ISSUE TITLE
Search results in "Dark Mode" in the libdoc page is very flashy

### ISSUE THREAD

**Issue by 98982872** [nim-lang/website#191]
In the dark mode, the result in the searchbox is bright yellow and the background is dark. Furthermore the light blue fonts do not help reading at all.

![image](https://i.imgur.com/I0XARor.png)

**Comment by KingDarBoja** [comment]
The search results is working locally with the background colour switch, probably the doc files need to be updated.

![image](https://user-images.githubusercontent.com/30560560/85928795-639adf80-b875-11ea-97a7-1a0f32f5dd1d.png)

**Comment by Vindaar** [comment]
To clarify @KingDarBoja's statement a little bit: The CSS file in use for the devel docs is fixed already. 
The real issue is that the CSS file in the normal Nim docs:

https://nim-lang.org/docs/nimdoc.out.css

contains the following piece of code:

```css
div.search_results {
  background-color: antiquewhite;
  margin: 3em;
  padding: 1em;
  border: 1px solid #4d4d4d;
}
```

which should actually be (and is on Nim devel here:
https://nim-lang.org/docs/nimdoc.out.css
):
```css
div.search_results {
  background-color: var(--third-background);
  margin: 3em;
  padding: 1em;
  border: 1px solid #4d4d4d;
}
```

Very well possible that this is clear to more web versed people, but it wasn't for me.
